import type { Metadata } from "next";
import { Geist, Geist_Mono, Nanum_Pen_Script, Open_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Footer from "./components/footer";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nanumPenScript = Nanum_Pen_Script({
  variable: "--font-nanum-pen-script",
  weight: "400",
  subsets: ["latin"]
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  weight: "400",
  subsets: ["latin"]
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Godspeed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nanumPenScript.variable} ${openSans.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <SessionProvider>
          <Nav />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
